"""
LangGraph State Definition for Agent State Management

Includes both legacy TypedDict states and the new message-based
AgenticState for ReACT agents.
"""

from typing import TypedDict, Optional, Annotated, List
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict, total=False):
    """
    Central state object passed between agents in the LangGraph workflow.
    
    Attributes:
        resume_text: Raw text extracted from the resume PDF
        skills: List of extracted skills from the resume
        user_id: Unique identifier for the user profile
        context: Dictionary to store file paths and additional context
        results: Dictionary to store results and logs from agents
    """
    resume_text: Optional[str]
    skills: list[str]
    user_id: Optional[str]
    context: dict
    results: dict


class AgenticState(TypedDict):
    """
    Message-based state for ReACT agents.

    Uses LangGraph's `add_messages` annotation so that new messages
    from each node are *appended* (not overwritten) automatically.

    Attributes:
        messages: The conversation/tool-call history for the ReACT loop.
        user_id: Authenticated user ID (passed through, never generated by LLM).
        metadata: Arbitrary dict for passing structured context between invocations.
    """
    messages: Annotated[List[BaseMessage], add_messages]
    user_id: Optional[str]
    metadata: dict
