"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/lib/AuthContext";
import * as api from "@/lib/api";
import type { TodayDataItem, SavedJob } from "@/lib/api";
import LiveStatusBadge from "@/components/LiveStatusBadge";
import JobCard from "@/components/JobCard";
import { Search, Loader2 } from "lucide-react";

interface RoadmapResource {
  name: string;
  url: string;
}

interface GraphNode {
  id: string;
  label: string;
  day: number;
  type: "concept" | "practice" | "project";
  description: string;
}

interface GraphEdge {
  source: string;
  target: string;
}

interface RoadmapGraph {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

interface RoadmapDetails {
  missing_skills: string[];
  graph: RoadmapGraph;
  resources: Record<string, RoadmapResource[]>;
}

interface ApplicationText {
  why_this_company: string;
  why_this_role: string;
  short_intro: string;
  cover_letter_opening: string;
  cover_letter_body: string;
  cover_letter_closing: string;
  key_achievements: string[];
  questions_for_interviewer: string[];
}

interface Job {
  id: string;
  score: number;
  title: string;
  company: string;
  description: string;
  link: string;
  location?: string;
  platform?: string;
  source?: string;
  status: string;
  action: string;
  tier?: string;
  ui_color?: string;
  roadmap_details: RoadmapDetails | null;
  application_text: ApplicationText | null;
  needs_improvement: boolean;
}

export default function JobsPage() {
  const router = useRouter();
  const { isAuthenticated, isLoading: authLoading, user } = useAuth();
  const [jobs, setJobs] = useState<Job[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [filteredJobs, setFilteredJobs] = useState<Job[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [savedJobIds, setSavedJobIds] = useState<Set<string>>(new Set());

  // Check saved jobs
  useEffect(() => {
    const fetchSavedJobs = async () => {
      if (!user?.id) return;
      try {
        const savedJobs = await api.getSavedJobs(user.id);
        const ids = new Set(savedJobs.map((j: SavedJob) => j.original_job_id));
        setSavedJobIds(ids);
      } catch (err) {
        console.error("Failed to fetch saved jobs:", err);
      }
    };
    if (isAuthenticated && user?.id) {
      fetchSavedJobs();
    }
  }, [isAuthenticated, user?.id]);

  const handleSaveJob = useCallback(async (job: any) => {
    if (!user?.id) return;
    try {
      await api.saveJob({
        user_id: user.id,
        original_job_id: job.id,
        title: job.title,
        company: job.company,
        description: job.description || "",
        link: job.link || "",
        score: job.score / 100, // Convert percentage back to 0-1
        roadmap_details: job.roadmap_details || null,
        full_job_data: job.full_job_data || null,
      });
      setSavedJobIds(prev => new Set([...prev, job.id]));
    } catch (err) {
      console.error("Failed to save job:", err);
      throw err;
    }
  }, [user?.id]);

  const handleUnsaveJob = useCallback(async (jobId: string) => {
    if (!user?.id) return;
    try {
      const savedJobs = await api.getSavedJobs(user.id);
      const savedJob = savedJobs.find((j: SavedJob) => j.original_job_id === jobId);
      if (savedJob) {
        await api.removeSavedJob(savedJob.id);
        setSavedJobIds(prev => {
          const newSet = new Set(prev);
          newSet.delete(jobId);
          return newSet;
        });
      }
    } catch (err) {
      console.error("Failed to unsave job:", err);
      throw err;
    }
  }, [user?.id]);

  // Fetch jobs from Agent 3 API
  useEffect(() => {
    const fetchJobs = async () => {
      if (!isAuthenticated) return;

      try {
        setIsLoading(true);
        const data = await api.getTodayJobs();
        const transformed = (data.jobs || []).map(
          (job: TodayDataItem, index: number) => ({
            id: job.id || String(index + 1),
            score: job.score,
            title: job.title,
            company: job.company,
            description: job.summary || "No description available",
            link: job.link,
            location: job.location,
            platform: job.platform,
            source: job.source,
            // Use 80% threshold (0.8) for high match
            status:
              job.score >= 0.8
                ? "Ready"
                : job.score >= 0.4
                ? "Gap Detected"
                : "Low Match",
            action: job.score >= 0.8 ? "Apply Now" : "View Roadmap",
            tier: job.score >= 0.8 ? "A" : job.score >= 0.4 ? "B" : "C",
            // Use roadmap directly from API (already generated by orchestrator)
            roadmap_details: job.roadmap || null,
            // Use application text directly from API (already generated by orchestrator)
            application_text: job.application_text || null,
            // Flag to show if improvement is needed
            needs_improvement: job.needs_improvement ?? job.score < 0.8,
          })
        );
        setJobs(transformed);
        setFilteredJobs(transformed);
      } catch (err) {
        console.error("Failed to fetch jobs:", err);
      } finally {
        setIsLoading(false);
      }
    };

    if (!authLoading) {
      if (!isAuthenticated) {
        router.push("/login");
      } else {
        fetchJobs();
      }
    }
  }, [isAuthenticated, authLoading, router]);

  // Filter jobs based on search query
  useEffect(() => {
    const filtered = jobs.filter(
      (job) =>
        job.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        job.company.toLowerCase().includes(searchQuery.toLowerCase()) ||
        job.description.toLowerCase().includes(searchQuery.toLowerCase())
    );
    setFilteredJobs(filtered);
  }, [searchQuery, jobs]);

  const getMatchPercentage = (score: number) => {
    return Math.round(score * 100);
  };

  // Loading state
  if (authLoading || isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#F7F5F0]">
        <div className="text-center">
          <Loader2 className="w-10 h-10 animate-spin text-[#D95D39] mx-auto mb-4" />
          <p className="text-gray-600">Loading jobs...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-canvas py-12 px-8">
      {/* Header Section */}
      <div className="mb-8 flex items-center justify-between">
        <h1 className="font-serif-bold text-4xl text-ink">Job Opportunities</h1>
        <LiveStatusBadge />
      </div>

      {/* Search/Filter Section */}
      <div className="max-w-4xl mx-auto mb-8">
        <div className="flex gap-3">
          <div className="flex-1 relative">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-secondary" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Filter jobs by title, company, or keywords..."
              className="w-full pl-12 pr-4 py-3 rounded-xl border bg-white text-ink focus:outline-none focus:ring-2"
              style={
                {
                  borderColor: "#E5E0D8",
                  "--tw-ring-color": "#D95D39",
                } as React.CSSProperties
              }
            />
          </div>
        </div>

        {/* Info message */}
        {jobs.length === 0 && (
          <div className="mt-4 p-4 rounded-lg bg-blue-50 border border-blue-200 text-blue-700 text-sm">
            Jobs are loaded from your dashboard strategy. Go to the{" "}
            <a href="/dashboard" className="underline font-medium">
              Dashboard
            </a>{" "}
            to generate personalized job matches.
          </div>
        )}
      </div>

      {/* Job List - Responsive Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 max-w-7xl mx-auto">
        {filteredJobs.length > 0 ? (
          filteredJobs.map((job) => (
            <JobCard
              key={job.id}
              id={job.id}
              companyName={job.company}
              jobTitle={job.title}
              matchScore={Math.round(job.score * 100)}
              description={job.description}
              link={job.link}
              roadmap_details={job.roadmap_details || undefined}
              fullJobData={{
                roadmap: job.roadmap_details || undefined,
                application_text: job.application_text || undefined,
                summary: job.description,
                platform: job.platform,
                source: job.source,
                type: "",
                needs_improvement: job.needs_improvement,
                location: job.location
              }}
              isSaved={savedJobIds.has(job.id)}
              onSave={handleSaveJob}
              onUnsave={handleUnsaveJob}
            />
          ))
        ) : jobs.length > 0 ? (
          <div className="lg:col-span-2 text-center py-12">
            <p className="text-secondary mb-4">No jobs match your filter.</p>
            <button
              onClick={() => setSearchQuery("")}
              className="px-4 py-2 rounded-lg border text-sm hover:bg-gray-50 transition-colors"
              style={{ borderColor: "#E5E0D8" }}
            >
              Clear Filter
            </button>
          </div>
        ) : (
          <div className="lg:col-span-2 text-center py-12">
            <Search className="w-12 h-12 mx-auto mb-4 text-secondary" />
            <p className="text-secondary mb-2">No job opportunities yet</p>
            <p className="text-sm text-secondary mb-4">
              Upload your resume and generate a strategy on the Dashboard to see
              personalized job matches
            </p>
            <a
              href="/dashboard"
              className="inline-block px-6 py-3 rounded-lg font-medium text-white transition-all hover:opacity-90"
              style={{ backgroundColor: "#D95D39" }}
            >
              Go to Dashboard
            </a>
          </div>
        )}
      </div>
    </div>
  );
}
